In [ ]:
import pandas
import numpy as np
import matplotlib.pyplot as plt
import math

In [ ]:
data=pandas.read_csv("C:\Machine_learning_lab\\Iris.csv") # it reads the Iris file as matrix

In [ ]:
data.head()


In [ ]:
SepalLengthCm = [] #it will strore the column of SepalLengthCm as vector
for i in np.arange(len(data['SepalLengthCm'])):
    SepalLengthCm.append(data['SepalLengthCm'][i])
SepalLengthCm = np.array(SepalLengthCm)

SepalWidthCm = [] #it will strore the column of SepalWidthCm as vector
for i in np.arange(len(data['SepalWidthCm'])):
    SepalWidthCm.append(data['SepalWidthCm'][i])
SepalWidthCm = np.array(SepalWidthCm)

PetalLengthCm = [] #it will strore the column of PetalLengthCm as vector
for i in np.arange(len(data['PetalLengthCm'])):
    PetalLengthCm.append(data['PetalLengthCm'][i])
PetalLengthCm = np.array(PetalLengthCm)

PetalWidthCm = [] #it will strore the column of PetalWidthCm as vector
for i in np.arange(len(data['PetalWidthCm'])):
    PetalWidthCm.append(data['PetalWidthCm'][i])
PetalWidthCm = np.array(PetalWidthCm)


In [62]:
t = np.cov((data['SepalLengthCm'],data['SepalWidthCm'],data['PetalWidthCm'],data['PetalWidthCm'])) # it computes the covariance matrix and stores in t

In [63]:
t

array([[ 0.68569351, -0.03926846,  0.5169038 ,  0.5169038 ],
       [-0.03926846,  0.18800403, -0.11798121, -0.11798121],
       [ 0.5169038 , -0.11798121,  0.58241432,  0.58241432],
       [ 0.5169038 , -0.11798121,  0.58241432,  0.58241432]])

In [65]:
eigval,eigvec=np.linalg.eig(t)
print(eigval)
print(eigvec)

[1.71098118e+00 2.29983738e-01 9.75612592e-02 1.18842125e-34]
[[ 5.80043561e-01 -5.84857860e-01  5.67001545e-01  7.98539020e-18]
 [-1.03475277e-01 -7.43325008e-01 -6.60878808e-01 -5.38342515e-17]
 [ 5.71332799e-01  2.29574842e-01 -3.47669706e-01 -7.07106781e-01]
 [ 5.71332799e-01  2.29574842e-01 -3.47669706e-01  7.07106781e-01]]


In [71]:
eigval[::-1].sort() #print the values in desending order
print("eigen values in desending order is:")
print(eigval)

eigen values in desending order is:
[1.71098118e+00 2.29983738e-01 9.75612592e-02 1.18842125e-34]
